### ISSUE TITLE
Cmake fail

### ISSUE THREAD

**Issue by Ye-Jinhong** [useredsa/MBPlib#1]
When following the usage:
```
cd example
cmake -S . -B build
cmake --build build
```
I came across a cmake fail after runing `cmake --build build`

error:
```
gmake[1]: *** No rule to make target '$path/MBPlib-master/build/all', needed by 'all'.  Stop.
gmake: *** [Makefile:91: all] Error 2
```

env:
cmake 3.22.6
ubuntu 20

**Comment by useredsa** [comment]
Dear @Ye-Jinhong,

I cannot reproduce your issue in another Linux distribution. I'll try in Ubuntu later today and let you know.

Best regards,

**Comment by Ye-Jinhong** [comment]
Thank you @useredsa .

And I tried on CentOS 8 again, it seems this error is not related to OS but something I don't know in environment.

Best wishes.

**Comment by useredsa** [comment]
Hello again @Ye-Jinhong,

I had no problem compiling the system in an Ubuntu distribution. Can you send me a the repository compressed after you did those three steps? Also, can you post your versions of `CMake` and `Make`/`gmake`?

Best regards,

**Comment by Ye-Jinhong** [comment]
Hello @useredsa ,

The compressed file is followed.
[MBPlib-master-record.zip](https://github.com/useredsa/MBPlib/files/14444996/MBPlib-master-record.zip)

env:
cmake: 3.22.1
make: 4.3
gcc: 9.4.0

By the way, could you give me your env version?

Thanksful.

**Comment by Ye-Jinhong** [comment]
Hi @useredsa ,

I changed the line 148 in example/build/CmakeFiles/Makefile2 from absolute path to relative path, which works. But I am confused  since Makefile2 is generated automatically by cmake.

Best wishes.

**Comment by useredsa** [comment]
Hello again @Ye-Jinhong,

Sorry for the late replay. I will answer different things.

> I changed the line 148 in example/build/CmakeFiles/Makefile2 from absolute path to relative path, which works. But I am confused since Makefile2 is generated automatically by cmake.

That line is an absolute path in my build. I checked the Makefiles (also the main one, `build/Makefile`) in the zip you sent me and mine and it seems that the main difference is that in yours paths are relative while in mine they are absolute. I guess it worked by changing that line because it made all the paths involved in that build relative, although I'm not sure. And by the way, cmake should always use absolute paths. See for example [this variable](https://cmake.org/cmake/help/v3.0/variable/CMAKE_USE_RELATIVE_PATHS.html), it no longer makes sense.

Also, the zip you sent me had all the executables already built inside `example/build`, so it seems that something failed at the end of the process to conclude the target `all` but the targets were built. Maybe you could try building a single target with `-t <target>`?

> cmake: 3.22.1
> make: 4.3
> gcc: 9.4.0
> 
> By the way, could you give me your env version?

I'm using very similar versions for cmake and make, only slightly newer.

```sh
$ cmake --version 
cmake version 3.28.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```sh
$ make --version 
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```sh
$ gcc --version # although I don't think it makes any difference
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I am glad you were finally able to build the library and I am sad that this is in this state. Right now I don't know why it happens and as it worked for me in Ubuntu as well. Are you perhaps using WSL?

Best regards,
Emilio

**Comment by Ye-Jinhong** [comment]
Hi @useredsa ,

Thank you for your reply. I realized that paths should all be either relative or absolute, so I changed the [CMakeLists.txt](https://github.com/useredsa/MBPlib/blob/master/example/CMakeLists.txt) in `./example/` with line 10-11 to `add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../ ${CMAKE_CURRENT_SOURCE_DIR}/top-build)`. This works well since all the paths generated are absolute path. 

I am not using WSL but a ubuntu server.

By the way, reminding you that links in [README.md](https://github.com/useredsa/MBPlib/blob/master/README.md#obtaining-traces) to obtaining traces are not working.

Thank you for taking the time out of your busy schedule to solve my problem.

Best wishes,
Ye

**Comment by useredsa** [comment]
Hello again,

> This works well since all the paths generated are absolute path.

I am glad you could find a workaround.

> By the way, reminding you that links in [README.md](https://github.com/useredsa/MBPlib/blob/master/README.md#obtaining-traces) to obtaining traces are not working.

Somehow the permission for the trace files did not allow the download of the DPC3 traces. The CBP5 traces should have been unaffected though. This is now solved. You can try downloading the DPC3 traces.

Best regards,
Emilio

**Comment by Ye-Jinhong** [comment]
Thank you @useredsa , 

It works well for me now.  I am going to close the issue.

Best wishes,
Ye
